Update containernetworking/cni to v0.8.1
k8snetworkplumbingwg/network-resources-injector pull request #76
Opened 2021-03-09 10:13 UTC by zshi-redhat

This commits updates containernetworking/cni to v0.8.1
to address CVE-2021-20206

Steps to update:
go get github.com/containernetworking/cni v0.8.1
go mod edit -replace github.com/containernetworking/cni=github.com/containernetworking/cni@v0.8.1
go mod tidy

Signed-off-by: Zenghui Shi <zshi@redhat.com>

2021-03-11 21:04 UTC, martinkennelly requested changes
Cosmetic but could you run go mod tidy as well. Thanks for this!

Clean output from snyk once I applied your patch:
```
✓ Tested 234 dependencies for known issues, no vulnerable paths found.
```

2021-03-12 00:56 UTC, zshi-redhat commented
> Cosmetic but could you run go mod tidy as well. Thanks for this!

I ran `go mod tidy`, didn't see it's adding extra changes to go files. I'm using:
$ go version
go version go1.15.6 linux/amd64

Did you get a different result running `go mod tidy`?

2021-03-12 09:59 UTC, martinkennelly commented
> > Cosmetic but could you run go mod tidy as well. Thanks for this!
> 
> I ran `go mod tidy`, didn't see it's adding extra changes to go files. I'm using:
> $ go version
> go version go1.15.6 linux/amd64
> 
> Did you get a different result running `go mod tidy`?

with go version go1.16 linux/amd64 and after running go mod tidy:

```
~/community/nri/network-resources-injector# git diff go.sum
diff --git a/go.sum b/go.sum
index faadbcc..101cda8 100644
--- a/go.sum
+++ b/go.sum
...........
 github.com/containernetworking/cni v0.7.0/go.mod h1:LGwApLUm2FpoOfxTDEeq8T9ipbpZ61X79hmU3w8FmsY=
-github.com/containernetworking/cni v0.7.1 h1:fE3r16wpSEyaqY4Z4oFrLMmIGfBYIKpPrHK31EJ9FzE=
 github.com/containernetworking/cni v0.7.1/go.mod h1:LGwApLUm2FpoOfxTDEeq8T9ipbpZ61X79hmU3w8FmsY=
...........
```
I guess there's changes across go versions for managing go.sum. Shouldn't gate this PR.

2021-03-12 09:59 UTC, martinkennelly approved these changes

2021-03-13 11:32 UTC, martinkennelly requested changes
@zshi-redhat will update this PR with replace directive

2021-03-13 14:08 UTC, zshi-redhat commented
> @zshi-redhat will update this PR with replace directive

Done. Thanks @martinkennelly !

2021-03-15 09:30 UTC, merged